#!/bin/bash

set -e

TO_INSTALL="bashrc vimrc tmux.conf"

for FILE in $TO_INSTALL
do
	if [ -f "~/.$FILE"]; 
	then
		echo "Replacing ~/.$FILE with symlink to dotfiles/$FILE"
		cp ~/.$FILE ~/.$FILE.old
		ln -sf `realpath $FILE` ~/.$FILE
	fi
done
